<a href="https://colab.research.google.com/github/EvanR2022/Stats-Notebook/blob/main/Evan%20Rudman_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

In [279]:
import numpy as np #we imported numpy to use its features.

### Loops

In [280]:
for i in range(100): #we created the variable i and told the computer to print the numbers 0-99 when we type i.
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [281]:
for i in range(5,8): #we changed the range of number to 5-8.
    print(i)

5
6
7


In [282]:
for i in range(3): #we changed the range to 3 and told to computer to write test number before each number.
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [283]:
def square(x): #we created the variable square x and gave it the value of x squared.
    return x**2

In [284]:
square(5) #we gave x the value to 5 to test our new variable.

25

In [285]:
square(square(2)) #we gave x the value of 2 and squared it twice.

16

In [286]:
square(square(square(2))) #we gave x the value of 2 and squared it three times.


256

In [287]:
square(123456) #we gave x the value of 123456 and tested our variable.

15241383936

In [288]:
square(square(5)) #we gave x the value of 5 and squared it twice.

625

In [289]:
def add_two(x): #we created the variable add two and gave it the value of x plus two.
    return x+2

In [290]:
add_two(5) #we gave x the value of 5 and tested our variable.

7

In [291]:
square(add_two(5)) #we gave x the value of 5, added two to it and then we squared it.

49

### Logical Branching

In [292]:
choice = "apple" #we created the variable choice and set it equal to apple.

In [293]:
if choice == "apple": #we told the computer that if we type apple then to give the response we told it otherwise it will say the other response.

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [294]:
choice = "orange" #we created another variable where our choice can also be orange.

In [295]:
if choice == "apple": #we told the computer what to respond with based off our choice.

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [296]:
choice = "apple" #we restated our choice being apple.

In [297]:
if choice == "apple": #we gave the computer more things to respond with based off our choice.

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [219]:
choice = input("Please enter your choice (i.e. apple): ") #we gave the computer a response to say when making our choice.

Please enter your choice (i.e. apple): apple


In [220]:
choice #we checked that the computer understood our choice.

'apple'

In [221]:
if choice == "apple": #we gave the computer responses to say based off our choice.

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

In [222]:
np.random.random() #we used the numpy random number generator.

0.5255959329495361

In [223]:
np.random.random() > 0.5 #we told the computer to give us either a response of true or false based on if the value is greater than or less than 0.5.

True

In [224]:
def flip_coin(): #we created the variable flip coin and we changed the response for greater than 0.5 to heads and less to tails.
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [225]:
flip_coin() #we tested our variable we created.

Tails


### Graphics Output

In [226]:
from IPython.core.display import display, HTML #we imported python so we could display images.

In [227]:
display(HTML('<h1>Hello, world!</h1>')) #we used html to display the text hello world.

In [228]:
def coin(): #we created the variable coin and gave it the value of eitherh 0 or 1.
  return np.random.randint(2)

In [229]:
coin() #we tested our variable.

1

In [230]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #we used html to display the image from the link we used.

In [231]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg' #we created the variables heads and tails and gave the computer links to show based off which variable is picked.
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [232]:
def show_img(img): #we created the variable show img and told the computer to display the image of the variable we pick.
  display(HTML('<img src=' + img + '>'))

In [233]:
show_img(heads) #We tested our variable and picked heads.

In [234]:
show_img(tails) #We tested our variable and picked tails.

In [235]:
def flip_coin(): #we created the variable flip coin and told it to display either heads or tails.

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [236]:
flip_coin() #we tested our variable

In [237]:
for i in range(5): #we flipped a coin 5 times.
    flip_coin()

In [238]:
#@title Coin Flip #we flipped a coin

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [239]:
def shuffle(x): #we created the variable shuffle and set it up to randomly generate numbers to replicate a deck of cards.
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [240]:
a = np.arange(52) #we set the range to 52 since there are 52 cards in a deck of cards.

In [241]:
shuffle(a) #we shuffled the deck.

array([36,  2, 42, 26, 24, 50, 11, 16, 37, 12, 29,  4,  6, 13, 31, 20, 40,
       51, 35, 38, 14, 17, 47,  0,  9,  3, 25,  1,  7, 15, 41, 33,  5, 49,
       34, 30, 18, 10, 39, 45, 27,  8, 23, 21, 32, 19, 44, 46, 22, 48, 43,
       28])

In [242]:
np.random.permutation(52) #we randomly displayed our range of 52 cards.

array([29, 48,  6, 34, 45, 46, 11, 20, 49, 30, 27,  8, 31, 12, 24, 47, 43,
       16, 22, 21, 33, 42, 44, 14, 13, 51, 25, 19,  3, 10, 28, 17, 32, 23,
        4,  9,  5, 36, 35, 26, 50, 39, 18,  7, 15, 41,  0, 38, 37,  2, 40,
        1])

### Speed Test

In [243]:
%%timeit
shuffle(a) #we used a feature to find the mean and standard deviation of our shuffling.

171 µs ± 5.33 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [244]:
%%timeit 
np.random.permutation(52) #we used a feature to find the mean and standard deviation of our random display of cards.

3.16 µs ± 42.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [245]:
import numpy as np #we imported numpy as np.

In [246]:
np.random.permutation(52) #we randomly displayed our range of 52 cards.

array([ 3, 15, 34,  0,  5, 30,  7, 10, 31, 18, 46, 41, 49, 42, 39, 38, 17,
        2, 20, 47,  1, 29, 12,  4,  8, 22, 11, 27, 26, 21, 45, 32, 14, 19,
       25, 33, 48, 16, 24,  6, 23, 50, 40, 28, 36, 13, 44, 51, 37,  9, 35,
       43])

In [247]:
cards = np.random.permutation(52) #we created the variable cards and gave it the value of a random display of 52 numbers.

In [248]:
cards #we tested our variable.

array([34, 18, 38,  8, 11, 43, 39, 35, 22, 51, 12, 42, 10, 26,  0, 25,  2,
        4, 32, 50, 27,  9, 44, 17,  5,  1, 40, 24, 13, 20, 45, 14, 41,  7,
       36, 21, 48, 19, 28, 37, 31, 23, 15, 30,  6, 16, 33, 29,  3, 46, 47,
       49])

In [249]:
cards[0] #we chose the first card in our deck.

34

In [250]:
cards[1] #we chose the second card in our deck.

18

In [251]:
cards[2] #we chose the third card in our deck.

38

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

#we imported images of a whole deck of cards.

In [252]:
np.arange(52).reshape(4,13) #we displayed our range of cards and used the reshape feature on numbers 4-13.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [253]:
np.arange(52).reshape(4,13)%13 #we displayed 4 rows of numbers from 0 to 12.

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [254]:
np.arange(52).reshape(4,13)//13 #we displayed 4 rows with the numbers 0,1,2, and 3 repeating 13 times in each row.

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [255]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #we created the variables suits and names and gave the names of each suit and card name in a deck of cards.
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [256]:
def card_name(card_number): #we created a variable so that when we say card name and give a number, it tells us the card that corresponds with that number.
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [257]:
card_name(0) #we asked the computer what the first card is

'Ace of Clubs'

In [258]:
card_name(51) #we asked the computer what the last card is.

'King of Diamonds'

In [259]:
cards = np.random.permutation(52) #we created the variable cards 

In [260]:
top_of_deck         = card_name(cards[0]) #we created the variables top of deck, second card in deck, and last card in deck and gave them cards to correspond with.
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [261]:
top_of_deck, second_card_in_deck, last_card_in_deck #we tested our variables to see their value.

('Eight of Clubs', 'King of Hearts', 'Two of Clubs')

In [262]:
for i in range(5): #we printed the first 5 cards in the deck
    print(card_name(cards[i]))

Eight of Clubs
King of Hearts
Five of Diamonds
Two of Diamonds
Eight of Diamonds


In [263]:
for i in range(15): #we printed the first 15 cards in the deck
    print(card_name(cards[i]))

Eight of Clubs
King of Hearts
Five of Diamonds
Two of Diamonds
Eight of Diamonds
Three of Hearts
Seven of Hearts
Ace of Clubs
Queen of Hearts
Six of Hearts
Nine of Clubs
Ten of Clubs
King of Spades
Seven of Clubs
Jack of Diamonds


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

#we imported a link to display images of our cards.

In [264]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" #we created the variables card url head amd tail and gave them links to display when entered.
card_url_tail = ".png"

In [265]:
suit = ['k','p','s','l'] #we created the variables suit and card and gave them values to correspond to.
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [266]:
i = np.random.randint(4) #we gave the variables i and j a numerical random value based off our set of cards.
j = np.random.randint(13)

In [267]:
i,j

(2, 8)

In [268]:
suit[i] #we tested our variable suit to get it to display a suit when we type in the variable i.

's'

In [269]:
card[j] #we tested our variable card to get it to display a card value when we type in the variable j.

'9'

In [270]:
from IPython.core.display import display, HTML #we imported python html so we can display images of our cards.

In [271]:
def show_img(img): #we created the variable show img so that when we type it in, it will display a card.
  display(HTML('<img src=' + img + '>'))

In [272]:
img = card_url_head + suit[i] + card[j] + card_url_tail #we defined the variable img to be the tail image of our selected card.

In [273]:
show_img(img) #we tested our variable show img to make sure it displays a photo of the selected card.

In [274]:
def card_image(card_number): #we created the variable card image so that when we type card image and a number it will display the suit and card value.
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [275]:
card_image(3) #we tested our variable card image with the card number of 3.

'k4'

In [276]:
img = card_url_head + card_image(3) + card_url_tail #we defined img to show us the image of the card when typed.

In [277]:
show_img(img) #we tested our variable show img to make sure it displays a photo of the selected card.

In [278]:
for i in range(52): #we displayed our whole deck of cards.
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)